server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: spring-boot-exam
    password: rz8BTX6HGcxwJGNx
    host:
    database-name: spring-boot-exam
    url: jdbc:mysql://${spring.datasource.host}:3306/${spring.datasource.database-name}
    hikari:
      max-lifetime: 500000

mybatis:
