server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: spring-boot-exam
    password: rz8BTX6HGcxwJGNx
    host:
    database-name: spring-boot-exam
    database-port: 3306
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.database-port}/${spring.datasource.database-name}
    hikari:
      max-lifetime: 500000

